### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by TangLu117** [rstyro/Springboot#19]
demo里放澳门赌场挺会玩

**Comment by rstyro** [comment]
> demo里放澳门赌场挺会玩

什么鬼？哪个demo有？

**Comment by TangLu117** [comment]
springboot-web 
index.html
<h1><a href="http://www.thymeleaf.org"  th:href="@{http://www.lrshuai.top}" th:text="${atext}">Thymeleaf</a></h1>

**Comment by TangLu117** [comment]
http://www.lrshuai.top

**Comment by rstyro** [comment]
> http://www.lrshuai.top

我擦，这个域名啥时候变成这样了，离谱哈

**Comment by rstyro** [comment]
> http://www.lrshuai.top

这个域名我以前用过，后面过期不用了，被别人占用了
